const $=s=>document.querySelector(s);let token=localStorage.getItem('lt_admin')||'',items=[];const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(url,opt={}){const headers={...(opt.headers||{}),'Content-Type':'application/json','Authorization':'Bearer '+token};const r=await fetch(url,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Error ${r.status}`);return d}
async function start(){if(!token)return;try{await api('/api/admin?action=check');show();await load()}catch{logout(false)}}function show(){$('#login').classList.add('hidden');$('#panel').classList.remove('hidden')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const btn=$('#loginBtn');btn.disabled=true;btn.innerHTML='Verificando <span class="spinner"></span>';$('#loginMsg').textContent='';try{const r=await fetch('/api/admin?action=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Error ${r.status}`);token=d.token;localStorage.setItem('lt_admin',token);show();await load();toast('Sesión iniciada correctamente')}catch(e){$('#loginMsg').textContent=e.message}finally{btn.disabled=false;btn.innerHTML='Entrar <span>→</span>'}};
async function load(){try{items=await api('/api/admin?action=list');if(!Array.isArray(items))items=[];render();$('#lastUpdate').textContent='Actualizado '+new Date().toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}catch(e){toast(e.message);if(/autoriz/i.test(e.message))logout(false)}}
function render(){const q=$('#adminSearch').value.toLowerCase().trim();const list=items.filter(p=>`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q));$('#count').textContent=items.length;$('#featuredCount').textContent=items.filter(p=>p.featured).length;$('#categoryCount').textContent=new Set(items.map(p=>p.category)).size;$('#list').innerHTML=list.map(p=>`<div class="item"><img src="${esc(p.image)}" onerror="this.src='https://placehold.co/100x100/091727/fff?text=LT'"><div class="item-main"><div class="item-title"><b>${esc(p.name)}</b>${p.badge?`<span>${esc(p.badge)}</span>`:''}</div><small>${esc(p.category)} · ${money(p.price)} · Stock: ${p.stock??0}${p.featured?' · ⭐ Destacado':''}</small></div><div class="actions"><button onclick="duplicateItem('${esc(p.id)}')">Duplicar</button><button onclick="edit('${esc(p.id)}')">Editar</button><button class="delete" onclick="del('${esc(p.id)}')">Borrar</button></div></div>`).join('')||'<div class="empty-list">No hay productos que coincidan.</div>'}
function edit(id){const p=items.find(x=>x.id===id);if(!p)return;$('#id').value=p.id;$('#name').value=p.name;$('#price').value=p.price;$('#stock').value=p.stock??0;$('#category').value=p.category;$('#badge').value=p.badge||'';$('#description').value=p.description||'';$('#imageUrl').value=/^https?:\/\//.test(p.image)?p.image:'';$('#featured').checked=!!p.featured;$('#preview').innerHTML=`<img src="${esc(p.image)}" alt="Vista previa">`;$('#title').textContent='Editar producto';$('#formMode').textContent='EDICIÓN';$('#cancel').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function reset(){$('#form').reset();$('#id').value='';$('#stock').value=1;$('#preview').innerHTML='';$('#imageUrl').value='';$('#title').textContent='Nuevo producto';$('#formMode').textContent='NUEVO';$('#cancel').classList.add('hidden');$('#msg').textContent=''}
async function del(id){const p=items.find(x=>x.id===id);if(!confirm(`¿Borrar “${p?.name||'este producto'}”?`))return;try{await api('/api/admin?action=delete',{method:'POST',body:JSON.stringify({id})});await load();toast('Producto eliminado')}catch(e){toast(e.message)}}
async function duplicateItem(id){const p=items.find(x=>x.id===id);if(!p)return;const copy={...p,id:crypto.randomUUID(),name:`${p.name} — copia`,featured:false};try{await api('/api/admin?action=save',{method:'POST',body:JSON.stringify(copy)});await load();toast('Producto duplicado')}catch(e){toast(e.message)}}
function read(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$('#form').onsubmit=async e=>{e.preventDefault();const btn=$('#saveBtn');btn.disabled=true;$('#msg').textContent='Guardando...';try{const old=items.find(p=>p.id===$('#id').value);let image=$('#imageUrl').value.trim()||old?.image||'';const file=$('#image').files[0];if(file){if(file.size>1200000)throw Error('La imagen debe pesar menos de 1.2 MB.');image=await read(file)}if(!image)throw Error('Selecciona una imagen o pega una URL.');const p={id:$('#id').value||crypto.randomUUID(),name:$('#name').value.trim(),price:Number($('#price').value),stock:Number($('#stock').value),category:$('#category').value,badge:$('#badge').value.trim(),description:$('#description').value.trim(),image,featured:$('#featured').checked};await api('/api/admin?action=save',{method:'POST',body:JSON.stringify(p)});reset();await load();toast('Producto guardado correctamente')}catch(e){$('#msg').textContent=e.message}finally{btn.disabled=false}};
$('#cancel').onclick=reset;$('#refresh').onclick=load;$('#adminSearch').addEventListener('input',render);$('#logout').onclick=()=>logout(true);function logout(showToast=true){localStorage.removeItem('lt_admin');token='';location.reload();if(showToast)toast('Sesión cerrada')}
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(items,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`luantech-catalogo-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data))throw Error('JSON inválido');if(!confirm(`Esto reemplazará el catálogo con ${data.length} productos. ¿Continuar?`))return;const r=await api('/api/admin?action=import',{method:'POST',body:JSON.stringify(data)});await load();toast(`${r.count} productos importados`)}catch(e){toast(e.message)}e.target.value=''};
$('#clearBtn').onclick=async()=>{if(!items.length)return;if(!confirm('¿Vaciar TODO el catálogo? Esta acción no se puede deshacer.'))return;try{await api('/api/admin?action=clear',{method:'POST',body:'{}'});await load();toast('Catálogo vacío')}catch(e){toast(e.message)}};
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove('show'),2400)}start();
