const $=s=>document.querySelector(s);let products=[],cart=JSON.parse(localStorage.getItem('lt_cart')||'[]');
const cfg=window.LUANTECH_CONFIG||{};const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:cfg.currency||'COP',maximumFractionDigits:0}).format(Number(n)||0);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const demo=[{id:'d1',name:'Smartphone LuanTech X1',price:899900,category:'Celulares',description:'Equipo de demostración para comenzar tu catálogo.',image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',featured:true,badge:'DEMO',stock:10},{id:'d2',name:'Audífonos Bluetooth Pro',price:129900,category:'Accesorios',description:'Audio inalámbrico para música y llamadas.',image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',featured:true,badge:'TOP',stock:12},{id:'d3',name:'Licuadora Multifunción',price:189900,category:'Electrodomésticos',description:'Potencia y practicidad para tu cocina.',image:'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=900&q=80',featured:true,stock:8},{id:'d4',name:'Lámpara LED inteligente',price:79900,category:'Hogar',description:'Iluminación moderna para tu espacio.',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',featured:true,stock:20}];
const icons={Celulares:'📱',Accesorios:'🎧',Electrodomésticos:'⚡',Hogar:'🏠'};const icon=c=>icons[c]||'🛍️';
async function load(){try{const r=await fetch('/api/products',{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();products=Array.isArray(d)&&d.length?d:demo}catch{products=demo}cart=cart.filter(c=>products.some(p=>p.id===c.id));saveCart();render()}
function render(){const cats=[...new Set(products.map(p=>p.category))];$('#categoryGrid').innerHTML=cats.map((c,i)=>`<button class="category reveal" style="--delay:${i*70}ms" onclick="setCat('${esc(c)}')"><div class="ico">${icon(c)}</div><b>${esc(c)}</b><small>${products.filter(p=>p.category===c).length} productos</small><span>→</span></button>`).join('');$('#categoryFilter').innerHTML='<option value="">Todas las categorías</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('#productTotal').textContent=`${products.length} productos`;draw();updateCart();observe()}
function setCat(c){$('#categoryFilter').value=c;location.hash='productos';draw()}
function draw(){const q=$('#search').value.toLowerCase().trim(),cat=$('#categoryFilter').value,sort=$('#sort').value;let list=products.filter(p=>(!cat||p.category===cat)&&(!q||`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(q)));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='az')list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='featured')list.sort((a,b)=>Number(b.featured)-Number(a.featured));if(sort==='newest')list.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('#empty').classList.toggle('hidden',!!list.length);$('#productGrid').innerHTML=list.map((p,i)=>`<article class="product reveal" style="--delay:${Math.min(i,7)*55}ms"><div class="product-media"><img class="product-img" loading="lazy" src="${esc(p.image)}" alt="${esc(p.name)}" onerror="this.src='https://placehold.co/800x600/091727/fff?text=LuanTech'">${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}<button class="heart" onclick="event.stopPropagation();favorite('${p.id}')">♡</button></div><div class="product-body"><div class="tag">${icon(p.category)} ${esc(p.category)}</div><h3>${esc(p.name)}</h3><p class="desc">${esc(p.description||'')}</p><div class="stock">${Number(p.stock)>0?'● Disponible':'● Consultar disponibilidad'}</div><div class="price">${money(p.price)}</div><div class="product-actions"><button class="buy" onclick="add('${p.id}')">Agregar</button><button onclick="detail('${p.id}')">Ver</button></div></div></article>`).join('');observe()}
function detail(id){const p=products.find(x=>x.id===id);if(!p)return;$('#productDetail').innerHTML=`<img class="detail-img" src="${esc(p.image)}" alt="${esc(p.name)}"><div class="detail"><p class="tag">${icon(p.category)} ${esc(p.category)}</p><h1>${esc(p.name)}</h1><p>${esc(p.description||'')}</p><div class="stock">${Number(p.stock)>0?`● ${p.stock} disponibles`:'● Consultar disponibilidad'}</div><div class="price">${money(p.price)}</div><button class="btn primary wide" onclick="add('${p.id}');closeModal('productModal')">Agregar al carrito</button></div>`;$('#productModal').classList.remove('hidden')}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const existing=cart.find(x=>x.id===id);if(existing)existing.qty=(existing.qty||1)+1;else cart.push({id,qty:1});saveCart();updateCart();toast('Producto agregado al carrito');openCart()}
function saveCart(){localStorage.setItem('lt_cart',JSON.stringify(cart))}function updateCart(){$('#cartCount').textContent=cart.reduce((s,x)=>s+(x.qty||1),0);drawCart()}
function drawCart(){$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>{const p=products.find(z=>z.id===x.id);if(!p)return '';return `<div class="cart-row"><img src="${esc(p.image)}"><div class="cart-main"><b>${esc(p.name)}</b><small>${money(p.price)}</small><div class="qty"><button onclick="qty(${i},-1)">−</button><b>${x.qty||1}</b><button onclick="qty(${i},1)">+</button></div></div><button class="remove" onclick="removeItem(${i})">×</button></div>`}).join(''):'<p class="muted">Tu carrito está vacío.</p>';$('#cartTotal').textContent=money(cart.reduce((s,x)=>{const p=products.find(z=>z.id===x.id);return s+(p?p.price*(x.qty||1):0)},0))}
function qty(i,n){cart[i].qty=Math.max(1,(cart[i].qty||1)+n);saveCart();updateCart()}function removeItem(i){cart.splice(i,1);saveCart();updateCart();toast('Producto eliminado')}function openCart(){drawCart();$('#cartModal').classList.remove('hidden')}function closeModal(id){$('#'+id).classList.add('hidden')}
function favorite(id){const key='lt_fav_'+id;localStorage.setItem(key,localStorage.getItem(key)==='1'?'0':'1');toast(localStorage.getItem(key)==='1'?'Añadido a favoritos':'Quitado de favoritos')}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2200)}
$('#checkout').onclick=()=>{if(!cart.length)return toast('Agrega al menos un producto');const name=$('#customerName').value.trim()||'Cliente';const lines=cart.map(x=>{const p=products.find(z=>z.id===x.id);return `• ${p.name} x${x.qty||1} — ${money(p.price*(x.qty||1))}`}).join('\n');const total=money(cart.reduce((s,x)=>{const p=products.find(z=>z.id===x.id);return s+p.price*(x.qty||1)},0));const text=`Hola LuanTech 👋%0ASoy ${encodeURIComponent(name)}.%0A%0AQuiero solicitar:%0A${encodeURIComponent(lines)}%0A%0ATotal: ${encodeURIComponent(total)}`;window.open(`https://wa.me/${cfg.whatsapp}?text=${text}`,'_blank')};
$('#searchToggle').onclick=()=>{$('#searchBar').classList.toggle('hidden');if(!$('#searchBar').classList.contains('hidden'))$('#search').focus()};$('#clearSearch').onclick=()=>{$('#search').value='';draw()};$('#search').addEventListener('input',draw);$('#categoryFilter').addEventListener('change',draw);$('#sort').addEventListener('change',draw);$('#cartBtn').onclick=openCart;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('lt_theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('lt_theme')==='light')document.body.classList.add('light');$('#waFooter').href=`https://wa.me/${cfg.whatsapp}`;
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});function observe(){document.querySelectorAll('.reveal:not(.visible)').forEach(x=>io.observe(x))};window.addEventListener('scroll',()=>$('#topBtn').classList.toggle('show',scrollY>500));$('#topBtn').onclick=()=>scrollTo({top:0,behavior:'smooth'});load();
